version: "3"
services:
  my-almalinux-php:
    platform: linux/arm64
    privileged: true
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 20022:20022
    volumes:
      - ./app:/var/www/html/
      - ./app:/var/www/backup_html/
      - ./seo_app:/home/seo/public_html/
      - ./kikuchi_app:/home/kikuchi/public_html/
    command: /sbin/init
